#!/usr/bin/env bash

set -e  # fail script on first error
sudo systemctl restart gunicorn
sudo systemctl daemon-reload
sudo systemctl restart gunicorn.socket gunicorn.service
sudo nginx -t
sudo systemctl restart nginx
